# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir = "content/en"
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1

[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "Academic"
  [zh.params]
    description = "Site description in Chinese..."

  [[zh.menu.main]]
    name = "主页"
    url = "#about"
    weight = 10

  [[zh.menu.main]]
    name = "文章"
    url = "#posts"
    weight = 20

  [[zh.menu.main]]
    name = "项目"
    url = "#projects"
    weight = 30

  [[zh.menu.main]]
    name = "论文"
    url = "#featured"
    weight = 40

  [[zh.menu.main]]
    name = "联系我"
    url = "#contact"
    weight = 60

  [[zh.menu.main]]
    name = "教程"
    url = "courses/"
    weight = 80